import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import { generateClient } from 'aws-amplify/data'
import './index.css'
import App from './App.tsx'
import { configureHotspotAmplify } from './lib/hotspotLayoutStore'

// Generated by `npx ampx sandbox` or pipeline deploy — must exist at runtime
import outputs from '../amplify_outputs.json'
import type { Schema } from '../amplify/data/resource'

try {
  Amplify.configure(outputs)
  const client = generateClient<Schema>()
  configureHotspotAmplify(client as any)
  console.log('PLM Console starting — Amplify Data client configured (MapLayout)')
} catch (err) {
  console.warn(
    'PLM Console starting — Amplify not configured (missing amplify_outputs.json or backend). Hotspot layout will use local cache only.',
    err
  )
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
)